/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyectotienda.view;

import com.proyectotienda.model.Cliente;
import com.proyectotienda.model.Producto;
import com.proyectotienda.model.VentaDetalle;
import com.proyectotienda.repository.ClienteRepository;
import com.proyectotienda.repository.VentaRepository;
import com.proyectotienda.service.CalculadorTotalVenta;
import com.proyectotienda.service.ClienteService;
import com.proyectotienda.service.ProductoService;
import com.proyectotienda.service.VentaService;

/**
 *
 * @author aleja
 */
public class MainWindow extends javax.swing.JFrame {
    // Lógica básica para ventas
    private java.util.List<VentaDetalle> productosVentaActual = new java.util.ArrayList<>();
    private Cliente clienteSeleccionado = null;
    private java.util.List<java.util.List<VentaDetalle>> ventasRealizadas = new java.util.ArrayList<>(); // Solo para mantener ventas en memoria si se requiere
    // Lógica básica para productos
    private java.util.List<Producto> listaProductos = new java.util.ArrayList<>();
    private javax.swing.table.DefaultTableModel productosTableModel;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());
    private VentaService ventaService;
    private ClienteService clienteService;
    private ProductoService productoService;

    // Lógica básica para clientes
    private java.util.List<Cliente> listaClientes = new java.util.ArrayList<>();
    private javax.swing.table.DefaultTableModel clientesTableModel;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        inicializarServicios();
        cargarDatosIniciales();
        configurarTablaVentas();
        actualizarTablaVentas();
        actualizarTotalVenta();

        // Configurar modelo de tabla para productos
        productosTableModel = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Código", "Nombre", "Talla", "Color", "Precio", "Stock"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaProductos.setModel(productosTableModel);
        actualizarTablaProductos();

        // Configurar modelo de tabla para clientes
        clientesTableModel = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Id", "Nombre", "Email", "Teléfono"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaClientes.setModel(clientesTableModel);
        actualizarTablaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMenu = new javax.swing.JTabbedPane();
        tabProductos = new javax.swing.JPanel();
        btnGuardarProductos = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        btnActualizarProductos = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        btnEliminarProductos = new javax.swing.JButton();
        lblProductos = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        scrollTablaProductos = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        txtNombreProductos = new javax.swing.JTextField();
        lblNombreProductos = new javax.swing.JLabel();
        lblTalla = new javax.swing.JLabel();
        txtTalla = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblListadoProductos = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        tabVentas = new javax.swing.JPanel();
        comboBoxCliente = new javax.swing.JComboBox<>();
        lblVentas = new javax.swing.JLabel();
        lblSeleccionarCliente = new javax.swing.JLabel();
        btnAgregarProductos = new javax.swing.JButton();
        scrollVentas = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        lblFechaVenta = new javax.swing.JLabel();
        lblTotalVenta = new javax.swing.JLabel();
        btnGuardarVenta = new javax.swing.JButton();
        btnCancelarVenta = new javax.swing.JButton();
        tabCanal = new javax.swing.JPanel();
        btnGuardarClientes = new javax.swing.JButton();
        btnActualizarClientes = new javax.swing.JButton();
        btnEliminarClientes = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        scrollTablaClientes = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        lblListadoClientes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabMenu.setToolTipText("");
        tabMenu.setName(""); // NOI18N

        btnGuardarProductos.setText("Guardar");
        btnGuardarProductos.addActionListener(this::btnGuardarProductosActionPerformed);

        btnActualizarProductos.setText("Actualizar");
        btnActualizarProductos.addActionListener(this::btnActualizarProductosActionPerformed);

        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio.setText("Precio:");

        btnEliminarProductos.setText("Eliminar");
        btnEliminarProductos.addActionListener(this::btnEliminarProductosActionPerformed);

        lblProductos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblProductos.setText("Gestion de Productos");

        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigo.setText("Codigo:");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollTablaProductos.setViewportView(tablaProductos);

        lblNombreProductos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreProductos.setText("Nombre:");

        lblTalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTalla.setText("Talla:");

        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCantidad.setText("Cantidad:");

        lblListadoProductos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblListadoProductos.setText("Listado Productos");

        lblColor.setText("Color:");

        txtColor.addActionListener(this::txtColorActionPerformed);

        javax.swing.GroupLayout tabProductosLayout = new javax.swing.GroupLayout(tabProductos);
        tabProductos.setLayout(tabProductosLayout);
        tabProductosLayout.setHorizontalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductosLayout.createSequentialGroup()
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabProductosLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblProductos))
                    .addGroup(tabProductosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblListadoProductos)))
                    .addGroup(tabProductosLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnGuardarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnActualizarProductos)
                        .addGap(35, 35, 35)
                        .addComponent(btnEliminarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabProductosLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombreProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(txtCodigo)
                            .addComponent(txtTalla)
                            .addComponent(txtPrecio)
                            .addComponent(txtCantidad)
                            .addComponent(txtColor))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        tabProductosLayout.setVerticalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblProductos)
                .addGap(35, 35, 35)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTalla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor))
                .addGap(34, 34, 34)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProductos)
                    .addComponent(btnActualizarProductos)
                    .addComponent(btnEliminarProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lblListadoProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        tabMenu.addTab("Productos", tabProductos);

        comboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblVentas.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblVentas.setText("Gestion de Ventas");

        lblSeleccionarCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSeleccionarCliente.setText("Seleccionar cliente:");

        btnAgregarProductos.setText("Agregar productos");

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollVentas.setViewportView(tablaVentas);

        lblFechaVenta.setText("Aqui va la fecha");

        lblTotalVenta.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblTotalVenta.setText("Aqui va el valor total de la compra");

        btnGuardarVenta.setText("Guardar");

        btnCancelarVenta.setText("Cancelar");

        javax.swing.GroupLayout tabVentasLayout = new javax.swing.GroupLayout(tabVentas);
        tabVentas.setLayout(tabVentasLayout);
        tabVentasLayout.setHorizontalGroup(
            tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVentasLayout.createSequentialGroup()
                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTotalVenta)
                        .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabVentasLayout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(lblVentas))
                            .addGroup(tabVentasLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFechaVenta)
                                    .addGroup(tabVentasLayout.createSequentialGroup()
                                        .addComponent(btnAgregarProductos)
                                        .addGap(206, 206, 206))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabVentasLayout.createSequentialGroup()
                                        .addComponent(lblSeleccionarCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(tabVentasLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(scrollVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tabVentasLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnGuardarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnCancelarVenta)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        tabVentasLayout.setVerticalGroup(
            tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVentasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblVentas)
                .addGap(41, 41, 41)
                .addComponent(lblFechaVenta)
                .addGap(18, 18, 18)
                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeleccionarCliente)
                    .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAgregarProductos)
                .addGap(45, 45, 45)
                .addComponent(scrollVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotalVenta)
                .addGap(44, 44, 44)
                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarVenta)
                    .addComponent(btnGuardarVenta))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        tabMenu.addTab("Ventas", tabVentas);

        btnGuardarClientes.setText("Guardar");
        btnGuardarClientes.addActionListener(this::btnGuardarClientesActionPerformed);

        btnActualizarClientes.setText("Actualizar");

        btnEliminarClientes.setText("Eliminar");
        btnEliminarClientes.addActionListener(this::btnEliminarClientesActionPerformed);

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("Id:");

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email:");

        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefono.setText("Telefono:");

        lblClientes.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblClientes.setText("Gestion de Clientes");

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollTablaClientes.setViewportView(tablaClientes);

        lblListadoClientes.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblListadoClientes.setText("Listado Clientes");

        javax.swing.GroupLayout tabCanalLayout = new javax.swing.GroupLayout(tabCanal);
        tabCanal.setLayout(tabCanalLayout);
        tabCanalLayout.setHorizontalGroup(
            tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCanalLayout.createSequentialGroup()
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCanalLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabCanalLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnActualizarClientes)
                                .addGap(43, 43, 43)
                                .addComponent(btnEliminarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabCanalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreCliente)
                                    .addComponent(txtId)
                                    .addComponent(txtEmail)
                                    .addComponent(txtTelefono)))))
                    .addGroup(tabCanalLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lblClientes))
                    .addGroup(tabCanalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListadoClientes)
                            .addComponent(scrollTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        tabCanalLayout.setVerticalGroup(
            tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCanalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblClientes)
                .addGap(38, 38, 38)
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addGap(26, 26, 26)
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarClientes)
                    .addComponent(btnActualizarClientes)
                    .addComponent(btnGuardarClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(lblListadoClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        tabMenu.addTab("Clientes", tabCanal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClientesActionPerformed
        // Agregar cliente de forma básica
        try {
            int id = Integer.parseInt(txtId.getText().trim());
            String nombre = txtNombreCliente.getText().trim();
            String email = txtEmail.getText().trim();
            String telefono = txtTelefono.getText().trim();
            if (nombre.isEmpty()) return;
            Cliente nuevo = new Cliente(id, nombre, email, telefono);
            listaClientes.add(nuevo);
            actualizarTablaClientes();
            limpiarCamposCliente();
        } catch (NumberFormatException e) {
            // Ignorar entrada inválida
        }
    }//GEN-LAST:event_btnGuardarClientesActionPerformed

    private void btnEliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClientesActionPerformed
        // Eliminar cliente seleccionado
        int fila = tablaClientes.getSelectedRow();
        if (fila >= 0 && fila < listaClientes.size()) {
            listaClientes.remove(fila);
            actualizarTablaClientes();
            limpiarCamposCliente();
        }
    }//GEN-LAST:event_btnEliminarClientesActionPerformed

    private void btnGuardarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductosActionPerformed
        // Agregar producto de forma básica
        try {
            String codigo = txtCodigo.getText().trim();
            String nombre = txtNombreProductos.getText().trim();
            String talla = txtTalla.getText().trim();
            String color = txtColor.getText().trim();
            double precio = Double.parseDouble(txtPrecio.getText().trim());
            int stock = Integer.parseInt(txtCantidad.getText().trim());
            if (codigo.isEmpty() || nombre.isEmpty()) return;
            Producto nuevo = new Producto();
            nuevo.setCodigo(codigo);
            nuevo.setNombre(nombre);
            nuevo.setTalla(talla);
            nuevo.setColor(color);
            nuevo.setPrecio(precio);
            nuevo.setStock(stock);
            listaProductos.add(nuevo);
            actualizarTablaProductos();
            limpiarCamposProducto();
        } catch (NumberFormatException e) {
            // Ignorar entrada inválida
        }
    }//GEN-LAST:event_btnGuardarProductosActionPerformed

    private void btnEliminarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductosActionPerformed
        // Eliminar producto seleccionado
        int fila = tablaProductos.getSelectedRow();
        if (fila >= 0 && fila < listaProductos.size()) {
            listaProductos.remove(fila);
            actualizarTablaProductos();
            limpiarCamposProducto();
        }
    }//GEN-LAST:event_btnEliminarProductosActionPerformed

    private void btnActualizarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarProductosActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed
    // Actualiza la tabla de clientes con los datos en memoria
    private void actualizarTablaClientes() {
        clientesTableModel.setRowCount(0);
        for (Cliente c : listaClientes) {
            clientesTableModel.addRow(new Object[]{c.getId(), c.getNombre(), c.getEmail(), c.getTelefono()});
        }
    }

    // Limpia los campos de entrada de cliente
    private void limpiarCamposCliente() {
        txtId.setText("");
        txtNombreCliente.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
    }

    // Actualiza la tabla de productos con los datos en memoria
    private void actualizarTablaProductos() {
        productosTableModel.setRowCount(0);
        for (Producto p : listaProductos) {
            productosTableModel.addRow(new Object[]{p.getCodigo(), p.getNombre(), p.getTalla(), p.getColor(), p.getPrecio(), p.getStock()});
        }
    }

    // Limpia los campos de entrada de producto
    private void limpiarCamposProducto() {
        txtCodigo.setText("");
        txtNombreProductos.setText("");
        txtTalla.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
    }

    private void inicializarServicios() {
        this.ventaService = new VentaService(new VentaRepository(), new CalculadorTotalVenta());
        this.clienteService = new ClienteService(new ClienteRepository());
        this.productoService = new ProductoService();
        this.productosVentaActual = new java.util.ArrayList<>();
        this.clienteSeleccionado = null;
    }

    private void cargarDatosIniciales() {
        cargarClientesEnComboBox();
        lblFechaVenta.setText("Fecha: " + java.time.LocalDate.now().toString());
    }

    private void cargarClientesEnComboBox() {
        comboBoxCliente.removeAllItems();
        for (Cliente cliente : listaClientes) {
            comboBoxCliente.addItem(cliente.getNombre());
        }
    }

    private void configurarTablaVentas() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{"Producto", "Cantidad", "Precio Unitario", "Subtotal"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaVentas.setModel(model);
    }

    private void actualizarTablaVentas() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaVentas.getModel();
        model.setRowCount(0);
        for (VentaDetalle detalle : productosVentaActual) {
            model.addRow(new Object[]{
                detalle.getProducto().getNombre(),
                detalle.getCantidad(),
                detalle.getPrecioUnitario(),
                detalle.getSubtotal()
            });
        }
    }

    private void actualizarTotalVenta() {
        double total = 0.0;
        for (VentaDetalle detalle : productosVentaActual) {
            total += detalle.getSubtotal();
        }
        lblTotalVenta.setText("Total: $" + String.format("%.2f", total));
    }

    private void btnAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {
        if (listaProductos.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay productos disponibles");
            return;
        }
        // Crear lista de nombres de productos para el combo box
        String[] nombresProductos = listaProductos.stream()
            .map(Producto::getNombre)
            .toArray(String[]::new);
        String selectedProduct = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Seleccione un producto:",
            "Agregar Producto",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            nombresProductos,
            nombresProductos[0]
        );
        if (selectedProduct != null) {
            // Encontrar el producto seleccionado
            Producto producto = listaProductos.stream()
                .filter(p -> p.getNombre().equals(selectedProduct))
                .findFirst()
                .orElse(null);
            if (producto != null) {
                // Pedir cantidad
                String cantidadStr = javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Cantidad para " + producto.getNombre() + ":",
                    "1"
                );
                try {
                    int cantidad = Integer.parseInt(cantidadStr);
                    if (cantidad <= 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0");
                        return;
                    }
                    VentaDetalle detalle = new VentaDetalle(
                        java.util.UUID.randomUUID().toString(),
                        producto,
                        cantidad,
                        producto.getPrecio()
                    );
                    productosVentaActual.add(detalle);
                    actualizarTablaVentas();
                    actualizarTotalVenta();
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Cantidad inválida");
                }
            }
        }
    }

    private void btnGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {
        int clienteIndex = comboBoxCliente.getSelectedIndex();
        if (clienteIndex < 0 || clienteIndex >= listaClientes.size()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente");
            return;
        }
        if (productosVentaActual.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Agregue al menos un producto");
            return;
        }
        // Guardar la venta en memoria (opcional, aquí solo limpiamos)
        ventasRealizadas.add(new java.util.ArrayList<>(productosVentaActual));
        javax.swing.JOptionPane.showMessageDialog(this, "Venta guardada exitosamente");
        productosVentaActual.clear();
        comboBoxCliente.setSelectedIndex(-1);
        actualizarTablaVentas();
        actualizarTotalVenta();
    }

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {
        productosVentaActual.clear();
        comboBoxCliente.setSelectedIndex(-1);
        actualizarTablaVentas();
        actualizarTotalVenta();
    }

    private void comboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedIndex = comboBoxCliente.getSelectedIndex();
        if (selectedIndex >= 0 && selectedIndex < listaClientes.size()) {
            clienteSeleccionado = listaClientes.get(selectedIndex);
        } else {
            clienteSeleccionado = null;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarClientes;
    private javax.swing.JButton btnActualizarProductos;
    private javax.swing.JButton btnAgregarProductos;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnEliminarClientes;
    private javax.swing.JButton btnEliminarProductos;
    private javax.swing.JButton btnGuardarClientes;
    private javax.swing.JButton btnGuardarProductos;
    private javax.swing.JButton btnGuardarVenta;
    private javax.swing.JComboBox<String> comboBoxCliente;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblListadoClientes;
    private javax.swing.JLabel lblListadoProductos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreProductos;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblSeleccionarCliente;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotalVenta;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JScrollPane scrollTablaClientes;
    private javax.swing.JScrollPane scrollTablaProductos;
    private javax.swing.JScrollPane scrollVentas;
    private javax.swing.JPanel tabCanal;
    private javax.swing.JTabbedPane tabMenu;
    private javax.swing.JPanel tabProductos;
    private javax.swing.JPanel tabVentas;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreProductos;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
